name: Build Lakhya v2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npx cap sync

      - run: cd android && chmod +x gradlew && ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: lakhya-final-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk